---
exclude: [bundle]
defaults:
   -
    scope:
     path: ""
     type: pages
    values:
     layout: lamalayout
     title: FoLiA
     subtitle: Format for Linguistic Annotation
     author: Maarten van Gompel (proycon)
     keywords: folia, format for linguistic annotation, xml, tei, d-coi, clarin, clariah
     description: FoLiA is an XML-based format for Linguistic Annotation suitable for representing written language resources such as corpora. Its goal is to unify a variety of linguistic annotations in one single rich format, without committing to any particular standard annotation set.
     lang: en
     menu:
      - label: Home
        url: https://proycon.github.io/folia/
      - label: Source
        url: https://github.com/proycon/folia/
      - label: Documentation
        url: https://folia.readthedocs.io
      - label: Python Library
        url: https://pypi.python.org/pypi/folia
      - label: Python Library Documentation
        url: http://pynlpl.readthedocs.io/en/latest/folia.html
      - label: FoLiA Tools
        url: https://pypi.python.org/pypi/FoLiA-tools
     languages:
      - lang: en
        label: English
     #- lang: nl
     #  label: Nederlands
     #- lang: de
     #  label: Deutsch
     #- lang: fr
     #  label: Français
     #- lang: es
     #  label: Español
     #- lang: pt
     #  label: Português
     #- lang: tr
     #  label: Türkçe
---
